### PR TITLE
Make the Octokit client more configurable.

### PR DESCRIPTION
**Pull request by parkr**
At the moment, it only points to https://api.github.com, but it should be configurable for GitHub Enterprise to point to other API and Web endpoints.

/cc @jekyll/gh-pages @brandonblack

### CODE REVIEW

**Comment by parkr** [comment]
@benbalter By setting the relevant environment variables.

**Comment by benbalter** [comment]
Ahh, so what's descibed in https://github.com/jekyll/github-metadata#overrides isn't accurate today?

**Comment by parkr** [comment]
@benbalter if you set PAGES_API_URL, octokit wont use it without this patch. You *also* have to set the OCTOKIT_API_ENDPONT environment variable.

**Comment by benbalter** [comment]
@jekyllbot: merge

**Pull request merged**
