### PR TITLE
Allow pages values to be overwritable

### PR DESCRIPTION
**Pull request by parkr**
Support GitHub Enterprise.

/cc #5 @benbalter

### CODE REVIEW

**Comment by parkr** [comment]
@benbalter any thoughts?

**Comment by benbalter** [comment]
What do you think about using/mirroring [the Octokit env vars](https://github.com/octokit/octokit.rb#using-env-variables)?

**Comment by parkr** [comment]
> What do you think about using/mirroring the Octokit env vars?

A much easier route! Think they'll always be the same? If so, we can just delegate to Octokit.

**Comment by parkr** [comment]
@benbalter Updated ^^

**Pull request merged**
