### PR TITLE
Normalize whitespace across platforms

### PR DESCRIPTION
**Pull request by ashmaroli**
Attempt to fix EOL errors on AppVeyor

### CODE REVIEW

**Comment by pathawks** [comment]
Would it be better to do this in `.gitattributes`?

**Comment by ashmaroli** [comment]
> Would it be better to do this in `.gitattributes`?

Perhaps. But I don't think Sublime Text and the like would pick that up.. not sure. Will have to check..

**Comment by pathawks** [comment]
If you want to normalize `CRLF` vs `LF`, you can do that in `.gitattributes` and Git will take care of it all internally. If the goal has more to do with preserving whitespace at the end of lines for Markdown, this is the way to go :+1:

**Comment by ashmaroli** [comment]
Guys, I'm merging this since `script/cibuild` will not run completely on AppVeyor with current `master` as relayed from existing AppVeyor logs..

**Pull request merged**
