### PR TITLE
Enable auto_paginate for Octokit client

### LINKED ISSUE #16: Public Repos (and other collections) only have first 30 results?
In my markdown files, I am trying to display the names of all public repositories for a particular organization, but it appears that the collection values available in `site.github` only contain 30 entries (likely based on the API's spec that says it [by default] only returns 30).

    {% for repository in site.github.public_repositories %}
            <li>{{ repository.full_name }}</li>
    {% endfor %}

Is there anyway to access more than 30? Or what is the common approach for paginating these results? Is it something I do in Liquid or do I need to write some Ruby, etc.?

I am having a hard time finding information about this because "paginating" already has some relevance as Jekyll feature.

Thanks

### PR DESCRIPTION
**Pull request by parkr**
Fixes #16, replaces #17.

@jarrodparkes Try it now

### CODE REVIEW

**Comment by jarrodparkes** [comment]
that did it!

**Comment by jarrodparkes** [comment]
might we suggest an option to shut it on/off? or is it possible for me to do that already? (my newbish Ruby) isn't it part of the Gem?

**Comment by parkr** [comment]
This gem is meant to exactly mimic the current github pages metadata feature. It's technically overridable but I want to enforce what GitHub provides :)

**Comment by jarrodparkes** [comment]
<blockquote>It's technically overridable but I want to enforce what GitHub provides :)</blockquote>

With that in mind, how can I override it in my own project (so that you don't have to maintain a separate branch just for me? If this (auto-paginate set to true) can only be set in the Ruby gem, then how can I override it?

Best,
Jarrod

**Comment by parkr** [comment]
> how can I override it in my own project

This, unfortunately, won't be possible. We want it to be one way in all cases! Thanks for spotting the bug though :)

**Comment by jarrodparkes** [comment]
@parkr So what would you suggest as my workaround? Just use another tool/gem?

**Comment by parkr** [comment]
@jarrodparkes If you only want 30, you can limit your loop like this:

```liquid
{% for repo in site.github.repositories limit:30 %}
  <!-- output repo stuff here -->
{% endfor %}
```

**Pull request merged**
